cmake . -DCMAKE_CUDA_COMPILER=$CUDA_HOME/bin/nvcc \
  -DCMAKE_CUDA_HOST_COMPILER=$CXX \
  -DCMAKE_CUDA_FLAGS="-I$CUDA_HOME/include -D_GLIBCXX_USE_CXX11_ABI=1" \
  -DCMAKE_CXX_FLAGS="-I$CUDA_HOME/include -D_GLIBCXX_USE_CXX11_ABI=1" \
  -DFETCHCONTENT_SOURCE_DIR_PYBIND11=$PYBINDSRC \
  -DFETCHCONTENT_FULLY_DISCONNECTED=ON \
  -DGMP_INCLUDE_DIR=$GMPDEVDIR/include \
  -DGMP_LIBRARIES=$GMPLIBRARYDIR/lib/libgmp.so
